import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

const faqs = [
    {
        question: "How does Contro generate content?",
        answer: "Contro uses advanced AI algorithms to generate unique and relevant content based on the keywords or titles you provide."
    },
    {
        question: "Can I generate content from images in Contro?",
        answer: "Yes, Contro can analyze images and generate content based on their context and elements."
    },
    {
        question: "How does the content categorization work in Contro?",
        answer: "Contro automatically categorizes generated content based on its context, helping you organize it efficiently."
    },
    {
        question: "Are there any usage limits in Contro?",
        answer: "The Free Plan offers up to 10 content generations per week, while the Monthly and Annual plans allow unlimited content generation."
    },
    {
        question: "Is the content generated by Contro suitable for commercial use?",
        answer: "Yes, you can use the content generated by Contro for commercial purposes, though we recommend reviewing it for quality and accuracy."
    }
];


export default function FAQ() {
    return (
        <div className="mt-32 w-full max-w-4xl">
                <h1 className="text-center text-3xl"> Frequently Asked Questions </h1>
                <Accordion type="single" collapsible className="mt-6 w-full">
                    {faqs.map((faq, index) => (
                        <AccordionItem key={index} value={`faq-${index}`} className="border-b border-gray-700 rounded-lg p-4">
                            <AccordionTrigger className="text-gray-800 text-lg">{faq.question}</AccordionTrigger>
                            <AccordionContent className="text-gray-800">{faq.answer}</AccordionContent>
                        </AccordionItem>
                    ))}
                </Accordion>
            </div>
    )
}